document.write('<div class="jumpbox" id="jumpbox">');
document.write('<div class="top_left"></div>');
document.write('<div class="top_center"></div>');
document.write('<div class="top_right"></div>');
document.write('<div class="middle_left"></div>');
document.write('<div class="middle_center">');
document.write('<div class="close"><a href="javascript:;" id="jumpclose"></a></div>');
document.write('<p>您尚未登录，请按如下方式获得返利！</p>');
document.write('<div class="contain">');
document.write('<div class="pic"><img src="" id="jump_pic" /></div>');
document.write('<div class="fan"></div>');
document.write('<div class="detail" id="layer_goods" style=" display:none">原价：<span class="jump_price">--.--</span><br />返利：<span id="jump_back">--.--</span><br /></div>');
document.write('<div class="detail" id="layer_zg" style=" display:none">平均返利：<span class="jump_price">--.--</span><br /></div>');
document.write('<div class="detail" id="layer_mall" style=" display:none">最高返：<span class="jump_price">--.--</span><br /></div>');
document.write('<div class="clear"></div>');
document.write('</div><div class="help">');
document.write('<span><a href="" id="jump_href" target="_blank">不要返利，去看看>></a> </span>');
document.write('<a href="user/register.php" target="_blank">没有账号？那就先注册吧</a></div>');
document.write('<div class="login"><strong>如果您已经是网站会员？</strong><br />输入您的用户名和密码，会返利到该账户!<br />');
document.write('<div>');
document.write('<table width="523" border="0" cellpadding="0">');
document.write('<tr>');
document.write('<th scope="col">账号：<input name="username" id="loginuser" type="text" class="text"/></th>');
document.write('<th scope="col">密码：<input name="password" id="loginpwd" type="password" class="text"/></th>');
document.write('<th scope="col"><input type="submit" value="快速返利" class="smt" name="submits" onclick="checkLogin(1)" /></th>');
document.write('</tr>');
document.write('</table>');
document.write('</div>');
document.write('<span id="jump_logtips"></span>');
document.write('</div>');
document.write('</div>');
document.write('<div class="middle_right"></div>');
document.write('<div class="end_left"></div>');
document.write('<div class="end_center"></div>');
document.write('<div class="end_right">');
document.write('</div></div>');